name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coursera

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build all crates
        run: cargo build --workspace --verbose --release

      - name: Run all assignments
        run: |
          for crate in */Cargo.toml; do
            crate_name=$(basename $(dirname "$crate"))
            echo "Running $crate_name..."
            cargo run -p "$crate_name" --verbose --release
          done

      - name: Run all tests
        run: cargo test --workspace --verbose --release
